// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zaposleni.Plugins.EFCoreSqlServer;

#nullable disable

namespace Zaposleni.Plugins.EFCoreSqlServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250531135526_InicijalniCreate")]
    partial class InicijalniCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.ClanoviDomacinstva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumRodjenjaClana")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImeClana")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("PolClana")
                        .HasMaxLength(1)
                        .HasColumnType("NCHAR");

                    b.Property<string>("Roditelj")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("SroClana")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StatusClana")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("ZaposlenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZaposlenId");

                    b.ToTable("ClanoviDomacinstva");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumRodjenjaClana = new DateTime(1998, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImeClana = "Mirjana",
                            JMBG = "1202998123456",
                            PolClana = "Ž",
                            Roditelj = "Jelena",
                            SroClana = "Ćerka",
                            StatusClana = "",
                            ZaposlenId = 1
                        },
                        new
                        {
                            Id = 2,
                            DatumRodjenjaClana = new DateTime(1997, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImeClana = "Tihomir",
                            JMBG = "2309997654987",
                            PolClana = "M",
                            Roditelj = "Jelena",
                            SroClana = "Sin",
                            StatusClana = "",
                            ZaposlenId = 1
                        },
                        new
                        {
                            Id = 3,
                            DatumRodjenjaClana = new DateTime(2018, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImeClana = "Goran",
                            JMBG = "0906018557789",
                            PolClana = "M",
                            Roditelj = "Ivana",
                            SroClana = "Sin",
                            StatusClana = "",
                            ZaposlenId = 2
                        });
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.GrupaMestaTroskova", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Grupa")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("GrupeMestaTroskova");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Grupa = "01",
                            Naziv = "FIRMA"
                        },
                        new
                        {
                            Id = 2,
                            Grupa = "02",
                            Naziv = "GENERALNI DIREKTOR"
                        },
                        new
                        {
                            Id = 3,
                            Grupa = "03",
                            Naziv = "PROIZVODNJA"
                        });
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.Kvalifikacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LicniStepenKv")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Kvalifikacije");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LicniStepenKv = "I",
                            Naziv = "Visoka stručna sprema"
                        },
                        new
                        {
                            Id = 2,
                            LicniStepenKv = "II",
                            Naziv = "Srednja stručna sprema"
                        });
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.Mesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opstina")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostanskiBroj")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Mesta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Beograd",
                            Opstina = "Vračar",
                            PostanskiBroj = "11000"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Novi Sad",
                            Opstina = "Stari Grad",
                            PostanskiBroj = "21000"
                        });
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.OrganizacioneJedinice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GrupaMestaTroskovaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("OJ")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("GrupaMestaTroskovaId");

                    b.ToTable("OrganizacioneJedinice");

                    b.HasData(
                        new
                        {
                            Id = 28,
                            GrupaMestaTroskovaId = 1,
                            Naziv = "IT sektor",
                            OJ = "0.5.00"
                        },
                        new
                        {
                            Id = 29,
                            GrupaMestaTroskovaId = 3,
                            Naziv = "ProizvodnjaBG",
                            OJ = "1.0.03"
                        });
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.Sistematizacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Beneficirani_Radni_Staz")
                        .HasColumnType("int");

                    b.Property<int?>("Bodovi")
                        .HasColumnType("int");

                    b.Property<int?>("KlasifikacijaZanimanjaId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Koeficijent")
                        .HasColumnType("decimal(6,3)");

                    b.Property<int?>("KvalifikacijaId")
                        .HasColumnType("int");

                    b.Property<string>("NazivRadnogMesta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opis")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int?>("OrganizacioneJediniceId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Radno_Iskustvo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("KvalifikacijaId");

                    b.HasIndex("OrganizacioneJediniceId");

                    b.ToTable("Sistematizacije");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Beneficirani_Radni_Staz = 0,
                            Bodovi = 100,
                            Koeficijent = 2.5m,
                            KvalifikacijaId = 1,
                            NazivRadnogMesta = "Programer",
                            Opis = "Opis radnog mesta za programera.",
                            OrganizacioneJediniceId = 28,
                            Radno_Iskustvo = "5 godina"
                        },
                        new
                        {
                            Id = 2,
                            Beneficirani_Radni_Staz = 0,
                            Bodovi = 80,
                            Koeficijent = 1.85m,
                            KvalifikacijaId = 1,
                            NazivRadnogMesta = "Tehničar",
                            Opis = "Opis za tehničara.",
                            OrganizacioneJediniceId = 29,
                            Radno_Iskustvo = "3 godine"
                        });
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.UserPermission", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.Zaposlen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("A_P")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Adresa")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime?>("Kraj_RadnogOd")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KvalifikacijaId")
                        .HasColumnType("int");

                    b.Property<int?>("MestoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Pocetak_RadnogOd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Roditelj")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("SistematizacijeId")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Vrsta_RadnogOdnosa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KvalifikacijaId");

                    b.HasIndex("MestoId");

                    b.HasIndex("SistematizacijeId");

                    b.ToTable("Zaposleni");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumRodjenja = new DateTime(1987, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ime = "Marko",
                            JMBG = "2311487134221",
                            MestoId = 1,
                            Pocetak_RadnogOd = new DateTime(2025, 5, 31, 15, 55, 25, 950, DateTimeKind.Local).AddTicks(7723),
                            Prezime = "Negovanovic",
                            Roditelj = "Uros",
                            SistematizacijeId = 1
                        },
                        new
                        {
                            Id = 2,
                            DatumRodjenja = new DateTime(1960, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ime = "Ivan",
                            JMBG = "0210960849567",
                            MestoId = 1,
                            Pocetak_RadnogOd = new DateTime(2025, 5, 31, 15, 55, 25, 950, DateTimeKind.Local).AddTicks(7788),
                            Prezime = "Lazarevic",
                            Roditelj = "Dragan",
                            SistematizacijeId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Zaposleni_Blazor.CoreBusiness.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Zaposleni_Blazor.CoreBusiness.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zaposleni_Blazor.CoreBusiness.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Zaposleni_Blazor.CoreBusiness.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.ClanoviDomacinstva", b =>
                {
                    b.HasOne("Zaposleni_Blazor.CoreBusiness.Zaposlen", "Zaposlen")
                        .WithMany()
                        .HasForeignKey("ZaposlenId");

                    b.Navigation("Zaposlen");
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.OrganizacioneJedinice", b =>
                {
                    b.HasOne("Zaposleni_Blazor.CoreBusiness.GrupaMestaTroskova", "GrupaMestaTroskova")
                        .WithMany("OrganizacioneJedinice")
                        .HasForeignKey("GrupaMestaTroskovaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrupaMestaTroskova");
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.RolePermission", b =>
                {
                    b.HasOne("Zaposleni_Blazor.CoreBusiness.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.Sistematizacija", b =>
                {
                    b.HasOne("Zaposleni_Blazor.CoreBusiness.Kvalifikacija", "Kvalifikacija")
                        .WithMany()
                        .HasForeignKey("KvalifikacijaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Zaposleni_Blazor.CoreBusiness.OrganizacioneJedinice", "OrganizacionaJedinica")
                        .WithMany()
                        .HasForeignKey("OrganizacioneJediniceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kvalifikacija");

                    b.Navigation("OrganizacionaJedinica");
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.UserPermission", b =>
                {
                    b.HasOne("Zaposleni_Blazor.CoreBusiness.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zaposleni_Blazor.CoreBusiness.ApplicationUser", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.Zaposlen", b =>
                {
                    b.HasOne("Zaposleni_Blazor.CoreBusiness.Kvalifikacija", "Kvalifikacija")
                        .WithMany("Zaposleni")
                        .HasForeignKey("KvalifikacijaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Zaposleni_Blazor.CoreBusiness.Mesto", "Mesto")
                        .WithMany("Zaposleni")
                        .HasForeignKey("MestoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Zaposleni_Blazor.CoreBusiness.Sistematizacija", "Sistematizacije")
                        .WithMany()
                        .HasForeignKey("SistematizacijeId");

                    b.Navigation("Kvalifikacija");

                    b.Navigation("Mesto");

                    b.Navigation("Sistematizacije");
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.ApplicationUser", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.GrupaMestaTroskova", b =>
                {
                    b.Navigation("OrganizacioneJedinice");
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.Kvalifikacija", b =>
                {
                    b.Navigation("Zaposleni");
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.Mesto", b =>
                {
                    b.Navigation("Zaposleni");
                });

            modelBuilder.Entity("Zaposleni_Blazor.CoreBusiness.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
