// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zaposleni_API_Auth.Data;

#nullable disable

namespace Zaposleni_API_Auth.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250405183618_Init14_dodata4tbl")]
    partial class Init14_dodata4tbl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zaposleni_API_Auth.Models.ClanoviDomacinstva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumRodjenjaClana")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImeClana")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("PolClana")
                        .HasMaxLength(1)
                        .HasColumnType("CHAR");

                    b.Property<string>("Roditelj")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("SroClana")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StatusClana")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("ZaposleniId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZaposleniId");

                    b.ToTable("ClanoviDomacinstva");
                });

            modelBuilder.Entity("Zaposleni_API_Auth.Models.GrupaMestaTroskova", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Grupa")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("GrupeMestaTroskova");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Grupa = "01",
                            Naziv = "FIRMA"
                        },
                        new
                        {
                            Id = 2,
                            Grupa = "02",
                            Naziv = "GENERALNI DIREKTOR"
                        },
                        new
                        {
                            Id = 3,
                            Grupa = "03",
                            Naziv = "PROIZVODNJA"
                        });
                });

            modelBuilder.Entity("Zaposleni_API_Auth.Models.Kvalifikacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LicniStepenKv")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Kvalifikacije");
                });

            modelBuilder.Entity("Zaposleni_API_Auth.Models.Mesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opstina")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostanskiBroj")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Mesta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Beograd",
                            Opstina = "Vračar",
                            PostanskiBroj = "11000"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Novi Sad",
                            Opstina = "Stari Grad",
                            PostanskiBroj = "21000"
                        });
                });

            modelBuilder.Entity("Zaposleni_API_Auth.Models.OrganizacioneJedinice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GrMestaTroskovaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("OJ")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("GrMestaTroskovaId");

                    b.ToTable("OrganizacioneJedinice");
                });

            modelBuilder.Entity("Zaposleni_API_Auth.Models.Zaposlen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("A_P")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Adresa")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime?>("Kraj_RadnogOd")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KvalifikacijaId")
                        .HasColumnType("int");

                    b.Property<int?>("MestoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("Pocetak_RadnogOd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Roditelj")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Vrsta_RadnogOdnosa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KvalifikacijaId");

                    b.HasIndex("MestoId");

                    b.ToTable("Zaposleni");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumRodjenja = new DateTime(1987, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ime = "Marko",
                            JMBG = "2311487134221",
                            MestoId = 1,
                            Pocetak_RadnogOd = new DateTime(2025, 4, 5, 20, 36, 16, 379, DateTimeKind.Local).AddTicks(7502),
                            Prezime = "Negovanovic",
                            Roditelj = "Uros"
                        },
                        new
                        {
                            Id = 2,
                            DatumRodjenja = new DateTime(1960, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ime = "Ivan",
                            JMBG = "0210960849567",
                            MestoId = 2,
                            Pocetak_RadnogOd = new DateTime(2025, 4, 5, 20, 36, 16, 379, DateTimeKind.Local).AddTicks(7578),
                            Prezime = "Lazarevic",
                            Roditelj = "Dragan"
                        });
                });

            modelBuilder.Entity("Zaposleni_API_Auth.Models.ClanoviDomacinstva", b =>
                {
                    b.HasOne("Zaposleni_API_Auth.Models.Zaposlen", "Zaposleni")
                        .WithMany()
                        .HasForeignKey("ZaposleniId");

                    b.Navigation("Zaposleni");
                });

            modelBuilder.Entity("Zaposleni_API_Auth.Models.OrganizacioneJedinice", b =>
                {
                    b.HasOne("Zaposleni_API_Auth.Models.GrupaMestaTroskova", "GrMestaTroskova")
                        .WithMany("OrganizacioneJedinice")
                        .HasForeignKey("GrMestaTroskovaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrMestaTroskova");
                });

            modelBuilder.Entity("Zaposleni_API_Auth.Models.Zaposlen", b =>
                {
                    b.HasOne("Zaposleni_API_Auth.Models.Kvalifikacija", "Kvalifikacija")
                        .WithMany("Zaposleni")
                        .HasForeignKey("KvalifikacijaId");

                    b.HasOne("Zaposleni_API_Auth.Models.Mesto", "Mesto")
                        .WithMany("Zaposleni")
                        .HasForeignKey("MestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kvalifikacija");

                    b.Navigation("Mesto");
                });

            modelBuilder.Entity("Zaposleni_API_Auth.Models.GrupaMestaTroskova", b =>
                {
                    b.Navigation("OrganizacioneJedinice");
                });

            modelBuilder.Entity("Zaposleni_API_Auth.Models.Kvalifikacija", b =>
                {
                    b.Navigation("Zaposleni");
                });

            modelBuilder.Entity("Zaposleni_API_Auth.Models.Mesto", b =>
                {
                    b.Navigation("Zaposleni");
                });
#pragma warning restore 612, 618
        }
    }
}
